# Generated by Django 3.0.8 on 2020-07-18 18:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('questions', '0006_auto_20200717_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
