# Generated by Django 3.0.8 on 2020-07-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questionsmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
