# Generated by Django 3.0.8 on 2020-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionsmodel_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='quesiton_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
