# Generated by Django 3.0.8 on 2020-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questionsmodel_quesiton_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
