# Generated by Django 3.0.8 on 2020-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200720_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
