# Generated by Django 3.0.8 on 2020-07-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200720_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
