# Generated by Django 3.0.8 on 2020-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200720_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsmodel',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
