# Generated by Django 3.0.8 on 2020-07-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_remove_questionsmodel_quesiton_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='keyword',
        ),
    ]
