# Generated by Django 3.0.8 on 2020-08-09 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_app', '0002_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='books_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
