# Generated by Django 3.0.8 on 2020-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_books_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='meta_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета дескриптион'),
            preserve_default=False,
        ),
    ]
