# Generated by Django 3.0.8 on 2020-08-09 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='service_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
