# Generated by Django 3.0.8 on 2020-08-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicepost_users_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepost',
            old_name='users_like',
            new_name='service_like',
        ),
    ]
