# Generated by Django 3.0.8 on 2020-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200809_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepost',
            name='meta_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета дескриптион'),
            preserve_default=False,
        ),
    ]
