# Generated by Django 3.0.8 on 2020-07-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
