# Generated by Django 3.0.8 on 2020-08-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200809_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(default=1, max_length=250, verbose_name='Мета описание'),
            preserve_default=False,
        ),
    ]
