# Generated by Django 3.0.8 on 2020-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_keyword',
            field=models.CharField(default=1, max_length=250, verbose_name='Ключевые слова (ключ 1, ключ 2, ключ 3…)'),
            preserve_default=False,
        ),
    ]
